### PR TITLE
Mendix 6 version

### PR DESCRIPTION
**Pull request by JelteMX**
- Remove deprecations
- AMDify BarcodeScannerForPhoneGap
- Add development files (Grunt)
- Remove obsolete dist folder (new versions are added in test/widgets and included in releases)

### CODE REVIEW

**Comment by mlaponder** [comment]
We would like to avoid commiting mpk's to the repo altogether. The only thing that is needed is uploading a built mpk as a new release and rely on GitHub for tagging.

**Comment by JelteMX** [comment]
- Version number is up to you, I just made sure it was already bumped.
- Adding a dependency on Grunt is not necessary, but this is what we use at Community right now, based on what I created in the [generator-mendix](https://github.com/mendix/generator-mendix). Again, this is up to you.
- You have to commit an MPK to the repo, because this is part of `test/widgets` which is part of your test-project.

Just check what you can use from my pull request and update the widget :-)

**Comment by lvanengelen** [comment]
Yup, that was our booboo, should have done that already. Thanks again for
picking this up.

The widgets dir and mpk can just be created when setting up the project.

Op 4 dec. 2015 5:14 PM schreef "Jelte Lagendijk" notifications@github.com:

**Comment by JelteMX** [comment]
True, but in every widget repo we have included the MPK as well, so I suggest you guys do it here as well :-). Glad I could help. I'll keep an eye out, already have someone asking to fix the widget on the mxforum.

Edit: [The topic on the forum](https://mxforum.mendix.com/questions/9243/barcode-scanner-for-phonegap-not-working-in-Release-6)

**Comment by mlaponder** [comment]
We fixed the Mendix 6 compatibility issues and published a new version in the appstore. Thanks for helping out.

**Comment by JelteMX** [comment]
Awesome, great work :-)

**Pull request closed without merging**
